bicep:
	az bicep build -f aks-arm64/main.bicep 
	az bicep build -f aks-bicep-k8s/main.bicep 
	az bicep build -f aks-bicep-keda/01-aks/main.bicep 
	az bicep build -f aks-bicep/01-aks/main.bicep 
	az bicep build -f aks-open-service-mesh/main.bicep
	az bicep build -f aks-webapp-routing/main.bicep 
	az bicep build -f containerapps-bicep/main.bicep