apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-blob
  labels:
    app.kubernetes.io/name: go-blob
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: go-blob
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-blob
    spec:
      serviceAccountName: go-blob
      containers:
        - name: go-blob
          image: "ghcr.io/asw101/go-blob:daemon"
          imagePullPolicy: Always
          env:
          - name: AZURE_STORAGE_ACCOUNT_NAME
            valueFrom:
              secretKeyRef:
                name: az-storage-account
                key: AZURE_STORAGE_ACCOUNT_NAME
                optional: true
          - name: AZURE_STORAGE_PRIMARY_ACCOUNT_KEY
            valueFrom:
              secretKeyRef:
                name: az-storage-account
                key: AZURE_STORAGE_PRIMARY_ACCOUNT_KEY
                optional: true
                