apiVersion: policy.openservicemesh.io/v1alpha1
kind: IngressBackend
metadata:
  name: bookthief
  namespace: bookthief
spec:
  backends:
  - name: bookthief
    port:
      number: 14001 # targetPort of bookthief service
      protocol: http
  sources:
  - kind: Service
    namespace: app-routing-system
    name: nginx