apiVersion: policy.openservicemesh.io/v1alpha1
kind: IngressBackend
metadata:
  name: bookstore
  namespace: bookstore
spec:
  backends:
  - name: bookstore
    port:
      number: 14001 # targetPort of bookstore service
      protocol: http
  sources:
  - kind: Service
    namespace: app-routing-system
    name: nginx