apiVersion: v1
kind: Service
metadata:
  name: bookbuyer
  namespace: bookbuyer
  labels:
    app: bookbuyer
    service: bookbuyer
spec:
  ports:
  - name: http
    port: 14001
  selector:
    app: bookbuyer
    version: v1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookbuyer
  namespace: bookbuyer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: webapprouting.kubernetes.azure.com # managed nginx ingress class name
  rules:
  - http:
      paths:
      - path: /bookbuyer
        pathType: Prefix
        backend:
          service:
            name: bookbuyer
            port:
              number: 14001