apiVersion: v1
kind: Service
metadata:
  name: bookthief
  namespace: bookthief
  labels:
    app: bookthief
    service: bookthief
spec:
  ports:
  - name: http
    port: 14001
  selector:
    app: bookthief
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookthief
  namespace: bookthief
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: webapprouting.kubernetes.azure.com # managed nginx ingress class name
  rules:
  - http:
      paths:
      - path: /bookthief
        pathType: Prefix
        backend:
          service:
            name: bookthief
            port:
              number: 14001
