apiVersion: v1
kind: Service
metadata:
  name: bookstore
  namespace: bookstore
  labels:
    app: bookstore
    service: bookstore
spec:
  ports:
  - name: http
    port: 14001
  selector:
    app: bookstore
    version: v2
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstore
  namespace: bookstore
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: webapprouting.kubernetes.azure.com # managed nginx ingress class name
  rules:
  - http:
      paths:
      - path: /bookstore
        pathType: Prefix
        backend:
          service:
            name: bookstore
            port:
              number: 14001
---
apiVersion: policy.openservicemesh.io/v1alpha1
kind: IngressBackend
metadata:
  name: bookstore
  namespace: bookstore
spec:
  backends:
  - name: bookstore
    port:
      number: 14001 # targetPort of bookstore service
      protocol: http
  sources:
  - kind: Service
    namespace: app-routing-system
    name: nginx