bicep:
	az bicep build -f vm/vm.bicep
	az bicep build -f vm-flatcar-postgres/main.bicep
	az bicep build -f vm-mariner/vm.bicep
	az bicep build -f vm-mastodon/vm.bicep
	az bicep build -f vmss/vmss.bicep